Repository softeerbootcamp-3rd/Team3-33ma3, pull requests merged in 2024-02, with the labels that each got.

#5 패키지 구조, 도메인 클래스 구현 #4
  33ma3/.gitignore
  33ma3/build.gradle
  33ma3/gradle/wrapper/gradle-wrapper.jar
  33ma3/gradle/wrapper/gradle-wrapper.properties
  33ma3/gradlew
  33ma3/gradlew.bat
  33ma3/settings.gradle
  33ma3/src/main/java/softeer/be33ma3/Application.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/domain/BaseTimeEntity.java
  33ma3/src/main/java/softeer/be33ma3/domain/CarCategory.java
  33ma3/src/main/java/softeer/be33ma3/domain/CenterService.java
  33ma3/src/main/java/softeer/be33ma3/domain/Color.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/domain/Region.java
  33ma3/src/main/java/softeer/be33ma3/domain/SelectedCenterService.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/resources/application.properties
  33ma3/src/test/java/softeer/ma3/ApplicationTests.java
Labels: feat, sprint1

#18 React vite 환경 구축 #17
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: feat, sprint1

#19 공통 Response 구현 #16
  33ma3/src/main/java/softeer/be33ma3/response/DataResponse.java
  33ma3/src/main/java/softeer/be33ma3/response/SingleResponse.java
Labels: feat, sprint1

#25 application.yml 설정 #24
  33ma3/.gitignore
  33ma3/gradlew.bat
  33ma3/src/main/resources/application.properties
Labels: feat, sprint1

#27 styles 공통 변수 추가 #26
  .vite/deps_temp_cf0c4ed6/package.json
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/main.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: feat, sprint1

#30 .vite에 대한 .gitignore 내용 추가 #29
  .gitignore
Labels: feat, sprint1

#23 README에 서비스 설명 추가 #21
  README.md
Labels: docs, sprint1

#31 댓글 세부사항 조회 기능 구현 #22
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/response/DataResponse.java
  33ma3/src/main/java/softeer/be33ma3/response/SingleResponse.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
Labels: feat, sprint1

#32 Header Component 구현 #11
  src/App.jsx
  src/assets/33MA3_logo.png
  src/assets/alarm.png
  src/components/header/Header.jsx
  src/components/header/NavItem.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: feat, sprint1

#33 SubmitButton 기능 구현 #6
  package-lock.json
  package.json
  src/App.jsx
  src/components/SubmitButton.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: feat, sprint1

#34 ChipButton 기능 구현 #9
  src/components/ChipButton.jsx
Labels: feat, sprint1

#40 게시글 작성 기능 구현 #14
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/domain/PostPerCenter.java
  33ma3/src/main/java/softeer/be33ma3/domain/Region.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/repository/ImageRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostPerCenterRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/RegionRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/RegionService.java
  33ma3/src/test/java/softeer/be33ma3/controller/LocationControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: feat, sprint1

#37 댓글 생성 기능 구현 #2
  .idea/workspace.xml
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/OfferCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: feat, sprint1

#42 댓글 생성 요청 처리 기능 수정 #2
  .idea/workspace.xml
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
Labels: refactor, feat, sprint1

#47 Title 컴포넌트 구현
  src/components/title/HeadTitle.jsx
  src/components/title/OptionTitle.jsx
Labels: feat, sprint1

#43 Input 컴포넌트 구현
  src/components/image/ImageUpload.jsx
  src/components/image/PictureArea.jsx
  src/components/input/InputText.jsx
  src/components/input/TextArea.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: style, feat, sprint1

#46 게시글 세부사항 조회 기능 #3
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/CenterRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: feat, sprint1

#51 경매 구매 제시 컴포넌트 구현 #50
  src/assets/bidPaddle.png
  src/components/BidPaddle.jsx
Labels: feat, sprint1

#49 Comment 컴포넌트 구현#45
  src/components/Comment.jsx
  src/components/button/ChipButton.jsx
  src/components/button/SubmitButton.jsx
  src/components/input/InputText.jsx
  src/components/input/TextArea.jsx
  src/styles/theme.js
Labels: style, refactor, feat, sprint1

#48 이미지 저장 기능 구현 #1
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/config/S3Config.java
  33ma3/src/main/java/softeer/be33ma3/controller/ImageController.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ImageListDto.java
  33ma3/src/main/java/softeer/be33ma3/service/ImageService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/S3Service.java
  33ma3/src/test/java/softeer/be33ma3/controller/ImageControllerTest.java
  33ma3/src/test/resources/testImage/testImage.jpg
Labels: feat, sprint1

#53 현재 위치 설정을 위한 Modal 구현 #35
  public/index.html
  src/components/LocationModal.jsx
  src/components/ViewCurrentLocation.jsx
Labels: style, refactor, feat, sprint1

#57 댓글 생성시 실시간으로 글 작성자에게 새로운 댓글 리스트 응답 #36
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/config/WebSocketConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/WebSocketService.java
Labels: feat, sprint1

#59 견적 제시 댓글 수정 기능 #58
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/exception/UnauthorizedException.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/WebSocketService.java
Labels: feat, sprint1

#60 게시물 작성 페이지 구현 #55
  src/components/button/ChipButton.jsx
  src/components/button/SubmitButton.jsx
  src/components/header/Header.jsx
  src/components/input/InputText.jsx
  src/components/input/TextArea.jsx
  src/components/title/HeadTitle.jsx
  src/constants/layouts.js
  src/constants/options.js
  src/pages/CreatePage/components/ImageUpload.jsx
  src/pages/CreatePage/components/InputRange.jsx
  src/pages/CreatePage/components/Option.jsx
  src/pages/CreatePage/components/OptionItem.jsx
  src/pages/CreatePage/components/SelectCategory.jsx
  src/pages/CreatePage/index.jsx
  src/styles/GlobalStyle.js
Labels: fix, style, feat, sprint1

#66 로그인 기능 구현 #56
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/config/CorsConfig.java
  33ma3/src/main/java/softeer/be33ma3/config/WebConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/ImageController.java
  33ma3/src/main/java/softeer/be33ma3/controller/LocationController.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Center.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/CenterSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/LoginDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/MemberSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/exception/JwtTokenException.java
  33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUser.java
  33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUserArgumentResolver.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtProperties.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtProvider.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtService.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtToken.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/JwtAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/RefreshTokenAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/repository/MemberRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: feat, sprint1

#68 모든 센터 정보 내려주기 #64
  33ma3/src/main/java/softeer/be33ma3/controller/LocationController.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/service/LocationService.java
  33ma3/src/test/java/softeer/be33ma3/controller/ImageControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/domain/CenterTest.java
  33ma3/src/test/java/softeer/be33ma3/service/LocationServiceTest.java
Labels: feat, sprint1

#73 로그인 기능 리팩토링 #56
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/controller/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/CenterSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ClientSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/JwtTokenException.java
  33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUser.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/JwtAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/RefreshTokenAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/repository/MemberRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/WebSocketService.java
  33ma3/src/main/resources/application-dev.yml
Labels: feat, sprint1

#81 테스트 코드 작성 #67
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/CenterSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ClientSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/LoginDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/PostCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/test/java/softeer/be33ma3/controller/LocationControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/controller/MemberControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtProviderTest.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/MemberRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/LocationServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/MemberServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: test, sprint1

#75 견적 댓글 낙찰 처리 기능 구현 #74
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
Labels: feat, sprint1

#78 Modal 세부 기능 구현 #54
  src/components/LocationModal.jsx
  src/components/ViewCurrentLocation.jsx
  src/components/input/InputText.jsx
Labels: fix, style, refactor, feat, sprint1

#93 게시물 페이지 구현 #62
  src/assets/person.svg
  src/assets/speech_bubble.svg
  src/components/BidPaddle.jsx
  src/components/button/ChipButton.jsx
  src/components/header/Header.jsx
  src/components/image/Carousel.jsx
  src/components/image/PictureArea.jsx
  src/components/post/AuctionPrice.jsx
  src/components/post/Comment.jsx
  src/components/post/OptionItem.jsx
  src/components/post/OptionType.jsx
  src/components/post/Page.jsx
  src/components/title/HeadTitle.jsx
  src/constants/url.js
  src/pages/PostCreatePage/components/InputRange.jsx
  src/pages/PostCreatePage/components/ServiceList.jsx
  src/pages/PostCreatePage/index.jsx
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionResult.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/CarInfo.jsx
  src/pages/PostPage/components/Content.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/index.jsx
Labels: style, refactor, feat, sprint2

#88 게시물 수정, 삭제 기능 구현 #83 #84
  .idea/workspace.xml
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUserArgumentResolver.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/JwtAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/RefreshTokenAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/repository/ImageRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ImageService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/S3Service.java
  33ma3/src/test/java/softeer/be33ma3/repository/ImageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: feat, sprint2

#90 마감기한이 지난 게시글 done 처리 기능 구현
  33ma3/src/main/java/softeer/be33ma3/Application.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
Labels: feat, sprint2

#91 웹소켓 통신 방법 수정 #87
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/AvgPriceDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostWithAvgPriceDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostWithOffersDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/WebSocketService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/ExitMember.java
  33ma3/src/main/java/softeer/be33ma3/websocket/HandShakeInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketConfig.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
  33ma3/src/test/java/softeer/be33ma3/repository/OfferRepositoryTest.java
Labels: feat, sprint2

#96 문의하기 기능에 필요한 도메인 구현 #94
  33ma3/src/main/java/softeer/be33ma3/domain/ChatMessage.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatRoom.java
Labels: feat, sprint2

#98 CarCardItem 컴포넌트 구현 #61
  src/assets/comment.svg
  src/assets/deadline_completed.svg
  src/components/CarCardItem.jsx
  src/components/Timer.jsx
  src/components/button/ChipButton.jsx
  src/components/image/Carousel.jsx
Labels: style, feat, sprint2

#100 게시물 작성 페이지에 Modal 적용 및 오류 수정 #92
  index.html
  src/App.jsx
  src/components/LocationModal.jsx
  src/components/input/InputText.jsx
  src/pages/PostCreatePage/index.jsx
  src/styles/GlobalStyle.js
Labels: fix, refactor, feat, sprint2

#103 게시물 목록 조회 페이지 구현#99
  package-lock.json
  package.json
  src/assets/slide_in.svg
  src/assets/slide_out.svg
  src/components/CarCardItem.jsx
  src/components/Timer.jsx
  src/components/button/DropDownButton.jsx
  src/components/button/DropDownItemButton.jsx
  src/components/button/ToggleButton.jsx
  src/components/sidebar/SideBarContainer.jsx
  src/constants/layouts.js
  src/constants/options.js
  src/pages/PostPage/index.jsx
  src/pages/PostPageList/components/SideBar.jsx
  src/pages/PostPageList/index.jsx
Labels: fix, feat, sprint2

#104 로그인, 회원가입 기능 구현 #76
  index.html
  package-lock.json
  package.json
  src/assets/center_mode.svg
  src/assets/client_mode.svg
  src/components/AuthForm.jsx
  src/components/LocationModal.jsx
  src/components/input/InputText.jsx
  src/pages/AuthenticationPage.jsx
  src/pages/Root.jsx
  src/utils/auth.js
Labels: fix, feat, sprint2

#101 필터링 전 전체 게시글 목록 조회 기능 구현 #80
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostPerCenterRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
Labels: feat, sprint2

#105 문의 기능 구현 #97
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/config/WebSocketConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Alert.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatMessage.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatRoom.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ChatMessageDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/AlertRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatRoomRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/HandShakeInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
  33ma3/src/main/resources/application-dev.yml
Labels: feat, sprint2

#107 라우팅 구현 #63
  package-lock.json
  src/App.jsx
  src/components/AuthForm.jsx
  src/components/CarCardItem.jsx
  src/components/header/Header.jsx
  src/components/header/NavItem.jsx
  src/components/post/AuctionPrice.jsx
  src/pages/AuthenticationPage/AuthenticationPage.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/CenterListPage/index.jsx
  src/pages/ChatRoomPage/index.jsx
  src/pages/InquiryHistoryPage/index.jsx
  src/pages/PostListPage/components/SideBar.jsx
  src/pages/PostListPage/index.jsx
  src/pages/PostPage/index.jsx
  src/pages/Root.jsx
  src/styles/GlobalStyle.js
  src/utils/router.jsx
Labels: fix, style, feat, sprint2

#111 게시물 상세 페이지 라우팅 연결#63
  src/components/CarCardItem.jsx
  src/components/image/Carousel.jsx
  src/pages/PostCreatePage/index.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/CarInfo.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/index.jsx
  src/utils/auth.js
  src/utils/router.jsx
Labels: style, feat

#110 로그인, 회원가입 페이지로 변경 #108
  src/components/AuthForm.jsx
  src/components/header/Header.jsx
  src/components/input/InputText.jsx
  src/pages/AuthenticationPage/AuthenticationPage.jsx
  src/pages/Root.jsx
  src/utils/router.jsx
  vite.config.js
Labels: fix, style, refactor, feat, sprint2

#115 게시글 관련 추가 보완 #109
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostPerCenterRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: refactor, feat, sprint2

#114 로그인, 회원가입 예외 처리 #113
  src/components/AuthForm.jsx
  src/components/LocationModal.jsx
  src/components/ViewCurrentLocation.jsx
  src/components/header/Header.jsx
  src/constants/mapConstants.js
  src/constants/url.js
  src/pages/AuthenticationPage/AuthenticationPage.jsx
  src/pages/PostCreatePage/index.jsx
  src/pages/Root.jsx
  src/utils/auth.js
  src/utils/locationUtils.js
Labels: refactor, feat

#116 문의 내역 기능 구현 #106
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Alert.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatMessage.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatRoom.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ChatMessageRequestDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageResponseDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatRoomListDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/LoginSuccessDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatRoomRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/HandShakeInterceptor.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/MemberServiceTest.java
Labels: feat, sprint2

#118 다중 조건을 이용한 게시글 필터링 기능 구현 #102
  33ma3/.gitignore
  33ma3/build.gradle
  33ma3/src/main/java/softeer/be33ma3/config/QueryDSLConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepositoryImpl.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostPerCenterRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
Labels: feat, sprint2

#119 채팅 목록 기능 구현 #106
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/LocationController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatHistoryDto.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtProperties.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: feat, sprint2

#123 게시물 목록 필터링 구현 #122
  src/components/button/DropDownItemButton.jsx
  src/components/button/ToggleButton.jsx
  src/pages/PostListPage/components/SideBar.jsx
  src/pages/PostListPage/index.jsx
Labels: feat

#121 경매 화면 구현 #112
  src/assets/1st_prize.svg
  src/assets/fail.svg
  src/assets/success.svg
  src/components/LocationModal.jsx
  src/components/button/SubmitButton.jsx
  src/components/input/TextArea.jsx
  src/components/modal/ModalPortal.jsx
  src/components/post/AuctionPrice.jsx
  src/components/post/Comment.jsx
  src/components/post/OptionType.jsx
  src/constants/options.js
  src/constants/url.js
  src/pages/AuthenticationPage/AuthenticationPage.jsx
  src/pages/PostCreatePage/index.jsx
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionResult.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/CarInfo.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/OfferModal.jsx
  src/pages/PostPage/components/ResultModal.jsx
  src/pages/PostPage/index.jsx
  src/styles/GlobalStyle.js
  src/utils/auth.js
  src/utils/router.jsx
Labels: fix, feat

#129 에러 상태 메세지 이넘으로 관리하도록 수정 #125
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/exception/BusinessException.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/exception/ErrorCode.java
  33ma3/src/main/java/softeer/be33ma3/exception/JwtTokenException.java
  33ma3/src/main/java/softeer/be33ma3/exception/UnauthorizedException.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtProvider.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtService.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/JwtAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/jwt/intercepter/RefreshTokenAuthenticationInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/S3Service.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: refactor, feat, sprint2

#133 테스트 코드 작성 #67
  33ma3/src/main/java/softeer/be33ma3/domain/Center.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatMessage.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatRoom.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/domain/PostPerCenter.java
  33ma3/src/main/java/softeer/be33ma3/domain/Region.java
  33ma3/src/main/java/softeer/be33ma3/domain/Review.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatRoomRepository.java
  33ma3/src/test/java/softeer/be33ma3/controller/LocationControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatRoomRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ImageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: test, feat, sprint3

#132 센터 리뷰 작성 퍼블리싱#124
  src/assets/star.svg
  src/components/header/NavItem.jsx
  src/components/modal/ModalPortal.jsx
  src/components/post/StarRating.jsx
  src/pages/CenterInfoPage/components/CreateReviewModal.jsx
  src/pages/CenterInfoPage/components/ReviewComment.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/CenterListPage/components/CenterCardItem.jsx
  src/pages/CenterListPage/components/SideBar.jsx
  src/pages/CenterListPage/index.jsx
  src/pages/PostListPage/components/CarCardItem.jsx
  src/pages/PostListPage/index.jsx
  src/pages/PostPage/index.jsx
  src/styles/GlobalStyle.js
  src/utils/auth.js
  src/utils/router.jsx
Labels: fix, style, refactor, feat

#135 Offer 관련 테스트 코드 작성, 웹 소켓 관련 로그 추가, 평균 견적 제시가 계산 메소드 수정 #38
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/ExitMember.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
  33ma3/src/test/java/softeer/be33ma3/dto/response/OfferDetailDtoTest.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/OfferRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/OfferServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: style, test, refactor, sprint2

#138 센터 리뷰 작성 기능 구현 #126
  33ma3/src/main/java/softeer/be33ma3/controller/ReviewController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Review.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ChatMessageRequestDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ClientSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/OfferCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ReviewCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/AvgPriceDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageResponseDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/LoginSuccessDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ErrorCode.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/ReviewRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
Labels: feat, sprint3

#136 경매 통신 관련 오류 수정#134
  src/components/AuthForm.jsx
  src/components/button/ChipButton.jsx
  src/components/post/AuctionPrice.jsx
  src/pages/PostListPage/components/CarCardItem.jsx
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionResult.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/OfferModal.jsx
  src/pages/PostPage/components/ResultModal.jsx
  src/pages/PostPage/index.jsx
Labels: fix, style, refactor, feat, sprint3

#140 문의 목록 실시간 전송 기능 구현 #106
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/AllChatRoomDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatHistoryDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageResponseDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostWithAvgPriceDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ControllerAdvice.java
  33ma3/src/main/java/softeer/be33ma3/jwt/JwtProvider.java
  33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/ExitMember.java
  33ma3/src/main/java/softeer/be33ma3/websocket/ExitRoomMember.java
  33ma3/src/main/java/softeer/be33ma3/websocket/HandShakeInterceptor.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
Labels: refactor, feat, sprint3

#147 센터 리뷰글 삭제 기능 구현 #139
  33ma3/src/main/java/softeer/be33ma3/controller/ReviewController.java
  33ma3/src/main/java/softeer/be33ma3/exception/ErrorCode.java
  33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
Labels: feat, sprint3

#152 채팅 히스토리 기능 구현 #143
  src/components/post/Comment.jsx
  src/pages/ChatRoomPage/components/ChatHeader.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/ChatMessage.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
  src/pages/ChatRoomPage/index.jsx
  src/pages/PostPage/components/OfferList.jsx
Labels: fix, style, feat, sprint3

#154 offer, post, review 관련 클래스에서 센터 이름 필드 제거 반영 #151
  33ma3/src/main/java/softeer/be33ma3/domain/Center.java
  33ma3/src/main/java/softeer/be33ma3/domain/PostPerCenter.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/OfferCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ReviewCreateDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ErrorCode.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
Labels: refactor, sprint3

#156 유저의 프로필 사진 업로드 기능 구현 #150
  33ma3/src/main/java/softeer/be33ma3/config/WebConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ImageListDto.java
  33ma3/src/main/java/softeer/be33ma3/exception/ErrorCode.java
  33ma3/src/main/java/softeer/be33ma3/jwt/CurrentUserArgumentResolver.java
  33ma3/src/main/java/softeer/be33ma3/service/ImageService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/S3Service.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
  33ma3/src/test/java/softeer/be33ma3/service/MemberServiceTest.java
Labels: refactor, feat, sprint3

#159 리뷰 작성, 삭제 구현#137
  src/components/AuthForm.jsx
  src/components/Timer.jsx
  src/components/modal/ModalPortal.jsx
  src/hooks/useTimer.jsx
  src/pages/CenterInfoPage/components/CreateReviewModal.jsx
  src/pages/CenterInfoPage/components/ReviewComment.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/PostListPage/components/CarCardItem.jsx
  src/pages/PostPage/components/AuctionResult.jsx
  src/pages/PostPage/components/CarInfo.jsx
  src/pages/PostPage/components/CreateReviewModal.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/star/HalfStarItem.jsx
  src/pages/PostPage/components/star/StarInput.jsx
  src/pages/PostPage/index.jsx
  src/utils/router.jsx
Labels: fix, style, feat

#166 내가 쓴 게시물 필터링 구현#160
  src/constants/url.js
  src/pages/CenterInfoPage/components/ReviewComment.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/CenterListPage/components/CenterCardItem.jsx
  src/pages/CenterListPage/index.jsx
  src/pages/PostListPage/components/SideBar.jsx
  src/pages/PostListPage/index.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/OfferModal.jsx
Labels: fix, feat, sprint3

#161 채팅 메시지 전송 기능 구현 #144
  src/assets/chatSubmit.svg
  src/components/post/Comment.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
  src/pages/PostPage/components/OfferList.jsx
Labels: fix, refactor, feat, sprint3

#165 본인이 작성한 게시글 필터링, 댓글 목록 별점 높은 순 정렬 추가 구현 #157
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepositoryImpl.java
  33ma3/src/main/java/softeer/be33ma3/repository/ReviewRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ImageService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: refactor, feat, sprint3

#169 [FIX] 병합 중 충돌 해결
  33ma3/src/main/java/softeer/be33ma3/config/WebConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/ReviewController.java
  33ma3/src/main/java/softeer/be33ma3/domain/BaseTimeEntity.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/domain/Review.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/CenterSignUpDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OneReviewDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ShowAllReviewDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ShowCenterReviewsDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/post/PostCustomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/post/PostCustomRepositoryImpl.java
  33ma3/src/main/java/softeer/be33ma3/repository/post/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/review/ReviewCustomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/review/ReviewCustomRepositoryImpl.java
  33ma3/src/main/java/softeer/be33ma3/repository/review/ReviewRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/LocationService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
  33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
  33ma3/src/main/java/softeer/be33ma3/utils/StringParser.java
  33ma3/src/test/java/softeer/be33ma3/repository/OfferRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/OfferServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: bug, fix, sprint3

#168 문의 내역 관련 구현 및 수정 #142
  src/pages/ChatRoomPage/components/ChatHeader.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
  src/pages/ChatRoomPage/index.jsx
  src/utils/dateTimeHelper.js
Labels: refactor, feat, sprint3

#174 문의 내역 실시간 전송 수정 #149
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/utils/StringParser.java
Labels: feat, sprint3

#177 채팅 부분 퍼블리싱 수정#172
  src/components/post/AuctionPrice.jsx
  src/components/post/Page.jsx
  src/constants/url.js
  src/pages/ChatRoomPage/components/ChatHeader.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/ChatMessage.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageHeader.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
  src/pages/ChatRoomPage/index.jsx
  src/pages/PostListPage/components/CarCardItem.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/styles/GlobalStyle.js
Labels: fix, style

#175 센터가 작성한 댓글에 센터의 프로필 사진 링크 추가 #173
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/MemberRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
Labels: feat, sprint3

#182 센터 리뷰 작성 부분 api 연결 #178
  src/pages/CenterInfoPage/components/ReviewComment.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/CenterListPage/components/CenterCardItem.jsx
  src/pages/CenterListPage/components/SideBar.jsx
  src/pages/CenterListPage/index.jsx
Labels: feat, sprint3

#183 댓글 업데이트 시 실시간 데이터 전송 방식 변경, 웹소켓 통신 방식 보완 #180
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
Labels: refactor, feat, sprint3

#187 채팅 양방향으로 수정 + 소켓 핸들러 리팩토링
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/domain/Alert.java
  33ma3/src/main/java/softeer/be33ma3/dto/request/ChatMessageDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/ChatMessageResponseDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OneReviewDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/AlertRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketRepository.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketService.java
Labels: refactor, feat, sprint3

#189 경매 부분 웹 소켓 수정 반영#185
  src/components/modal/ModalPortal.jsx
  src/components/post/AuctionPrice.jsx
  src/components/post/Comment.jsx
  src/components/post/OfferSelectModal.jsx
  src/constants/url.js
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/OfferModal.jsx
  src/pages/PostPage/components/ResultModal.jsx
  src/styles/GlobalStyle.js
  src/utils/router.jsx
Labels: feat, sprint3

#191 센터 채팅 리다이랙션 관련 기능 구현 #188
  src/components/post/Comment.jsx
  src/pages/ChatRoomPage/components/ChatHeader.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
  src/pages/ChatRoomPage/index.jsx
  src/utils/auth.js
Labels: fix, feat, sprint3

#192 경매 웹소켓 통신 관련, 회원가입 프로필 첨부 관련 수정 #186
  33ma3/src/main/java/softeer/be33ma3/config/WebConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
Labels: fix, refactor, feat, sprint3

#197 회원가입시 프로필 사진 등록 기능 추가
  src/pages/AuthenticationPage/components/SignUp.jsx
  src/pages/AuthenticationPage/components/UploadProfile.jsx
Labels: feat, sprint3

#198 사이드바 수정, 이미지 업로드 css 수정 #195
  src/components/image/PictureArea.jsx
  src/pages/AuthenticationPage/components/UploadProfile.jsx
  src/pages/PostCreatePage/components/ImageUpload.jsx
  src/pages/PostCreatePage/components/ImageUploadCard.jsx
  src/pages/PostListPage/components/SideBar.jsx
Labels: feat, sprint3

#200 LocationModal 현 위치 불러오는 기능 주석처리 #199
  src/components/ViewCurrentLocation.jsx
  src/constants/mapConstants.js
Labels: fix, sprint3

#204 게시글, 챗 서비스 관련 리팩토링 #146
  33ma3/src/main/java/softeer/be33ma3/domain/Center.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatMessage.java
  33ma3/src/main/java/softeer/be33ma3/domain/ChatRoom.java
  33ma3/src/main/java/softeer/be33ma3/domain/Image.java
  33ma3/src/main/java/softeer/be33ma3/domain/Member.java
  33ma3/src/main/java/softeer/be33ma3/domain/Offer.java
  33ma3/src/main/java/softeer/be33ma3/domain/Post.java
  33ma3/src/main/java/softeer/be33ma3/domain/PostPerCenter.java
  33ma3/src/main/java/softeer/be33ma3/domain/Review.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/LastMessageDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/OfferDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostDetailDto.java
  33ma3/src/main/java/softeer/be33ma3/dto/response/PostThumbnailDto.java
  33ma3/src/main/java/softeer/be33ma3/repository/Chat/ChatMessageCustomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/Chat/ChatMessageCustomRepositoryImpl.java
  33ma3/src/main/java/softeer/be33ma3/repository/Chat/ChatMessageRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/Chat/ChatRoomRepository.java
  33ma3/src/main/java/softeer/be33ma3/repository/review/ReviewRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/MemberService.java
  33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
  33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRoomRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
Labels: refactor, sprint3

#203 채팅 기능 디테일 오류 수정 #202
  src/components/post/Comment.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/ChatMessage.jsx
  src/pages/ChatRoomPage/components/Message.jsx
Labels: fix, refactor, sprint3

#206 테스트 오류 수정#201
  src/components/header/NavItem.jsx
  src/components/input/InputText.jsx
  src/components/post/Comment.jsx
  src/components/post/StarRating.jsx
  src/pages/CenterInfoPage/index.jsx
  src/pages/PostCreatePage/index.jsx
  src/pages/PostListPage/components/SideBar.jsx
  src/pages/PostListPage/index.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
  src/pages/PostPage/components/OfferModal.jsx
  src/utils/router.jsx
Labels: fix, feat, sprint3

#207 https url 로 변경 #201
  src/components/header/NavItem.jsx
  src/constants/url.js
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
Labels: fix

#211 센터 회원가입시 위치 모달 사용 #210
  src/components/ViewCurrentLocation.jsx
  src/components/header/NavItem.jsx
  src/pages/AuthenticationPage/components/CenterAuthForm.jsx
  src/pages/AuthenticationPage/components/Login.jsx
  src/pages/AuthenticationPage/components/SignUp.jsx
  src/pages/AuthenticationPage/components/SignUpModal.jsx
  src/pages/CenterListPage/components/CenterCardItem.jsx
  src/pages/ChatRoomPage/components/ChatInput.jsx
  src/pages/PostCreatePage/components/MapModal.jsx
Labels: fix, feat, sprint3

#219 wss로 변경 #217
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
Labels: fix, sprint3

#225 최신 댓글로 스크롤 이동, 댓글 스크롤 이동, 캐러셀 구현 #224
  .gitignore
  package.json
  src/assets/arrow_left.png
  src/assets/arrow_right.png
  src/components/image/Carousel.jsx
  src/components/image/PictureArea.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/CarInfo.jsx
  src/pages/PostPage/components/OfferList.jsx
Labels: style, feat, sprint3

#229 지도 모달의 반경 관련 코드 수정 #227
  src/components/ViewCurrentLocation.jsx
  src/pages/PostCreatePage/components/MapModal.jsx
Labels: fix, sprint3

#226 채팅 관련 오류 수정 #223
  src/components/ViewCurrentLocation.jsx
  src/constants/options.js
  src/pages/ChatRoomPage/components/ChatList.jsx
  src/pages/ChatRoomPage/components/ChatMessage.jsx
  src/pages/ChatRoomPage/components/Message.jsx
  src/pages/ChatRoomPage/components/MessageList.jsx
Labels: fix, style, feat, sprint3

#228 게시글 관련 테스트 코드 작성 -> 작성, 수정, 삭제
  33ma3/src/main/java/softeer/be33ma3/config/CorsConfig.java
  33ma3/src/main/java/softeer/be33ma3/controller/ChatController.java
  33ma3/src/main/java/softeer/be33ma3/controller/LocationController.java
  33ma3/src/main/java/softeer/be33ma3/controller/MemberController.java
  33ma3/src/main/java/softeer/be33ma3/controller/OfferController.java
  33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  33ma3/src/main/java/softeer/be33ma3/controller/ReviewController.java
  33ma3/src/main/java/softeer/be33ma3/repository/post/PostRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  33ma3/src/main/java/softeer/be33ma3/websocket/WebSocketHandler.java
  33ma3/src/test/java/softeer/be33ma3/controller/MemberControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/domain/CenterTest.java
  33ma3/src/test/java/softeer/be33ma3/dto/response/OfferDetailDtoTest.java
  33ma3/src/test/java/softeer/be33ma3/jwt/JwtServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRoomRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/MemberRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/OfferRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/post/PostRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/LocationServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/MemberServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/OfferServiceTest.java
  33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
Labels: test, sprint3

#234 useWebSocket 커스텀 훅 구현#231
  src/components/header/Header.jsx
  src/hooks/useWebSocket.jsx
  src/pages/PostPage/components/AuctionAverageStatus.jsx
  src/pages/PostPage/components/AuctionStatus.jsx
  src/pages/PostPage/components/OfferList.jsx
Labels: fix, feat, sprint3

#232 채팅 관련(문의 서비스) 테스트 코드 작성 #230
  33ma3/src/main/java/softeer/be33ma3/repository/Chat/ChatRoomRepository.java
  33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  33ma3/src/test/java/softeer/be33ma3/controller/ChatControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/Chat/ChatMessageCustomRepositoryImplTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/Chat/ChatMessageRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/Chat/ChatMessageRoomRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRoomRepositoryTest.java
  33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
Labels: test, sprint3

#236 [REFACTOR]: .gitignore 폴더 이동
  .gitignore
  fe-dev/.gitignore
Labels: fix, sprint3

#246 채팅 수신확인 기능 수정 및 프로필 사진 추가 #245
  fe-dev/package-lock.json
  fe-dev/src/pages/ChatRoomPage/components/ChatList.jsx
  fe-dev/src/pages/ChatRoomPage/components/ChatMessage.jsx
  fe-dev/src/pages/ChatRoomPage/components/Message.jsx
  fe-dev/src/pages/ChatRoomPage/components/MessageList.jsx
  fe-dev/src/pages/ChatRoomPage/index.jsx
Labels: feat, sprint3, FE

#241 [FE] 문구 수정#240
  fe-dev/src/components/post/OfferSelectModal.jsx
  fe-dev/src/pages/PostPage/components/OfferModal.jsx
Labels: refactor, feat, sprint3, FE

#248 jacoco 설정, 테스트 코드 작성 #247
  be-dev/33ma3/build.gradle
  be-dev/33ma3/src/main/java/softeer/be33ma3/dto/request/CenterSignUpDto.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/controller/MemberControllerTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/MemberRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/MemberServiceTest.java
Labels: test, sprint3, BE

#253 테스트코드 작성 #148
  be-dev/33ma3/src/main/java/softeer/be33ma3/controller/PostController.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageCustomRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageCustomRepositoryImpl.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ChatMessageRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ChatRoomRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/OfferRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/PostCustomRepositoryImpl.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/PostPerCenterRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/PostRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ReviewCustomRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ReviewCustomRepositoryImpl.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/repository/ReviewRepository.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/service/ChatService.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/service/OfferService.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/service/PostService.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/service/ReviewService.java
  be-dev/33ma3/src/main/java/softeer/be33ma3/service/SchedulingService.java
  be-dev/33ma3/src/main/resources/application-dev.yml
  be-dev/33ma3/src/test/java/softeer/be33ma3/controller/OfferControllerTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/controller/PostControllerTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/controller/ReviewControllerTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageCustomRepositoryImplTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/ChatMessageRoomRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/OfferRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/PostRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/repository/ReviewRepositoryTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/ChatServiceTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/OfferServiceTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/PostServiceTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/ReviewServiceTest.java
  be-dev/33ma3/src/test/java/softeer/be33ma3/service/SchedulingServiceTest.java
Labels: test, sprint3, BE
